/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fishappmidnight;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.io.PrintWriter; //Imports a 'PrintWriter
import java.io.FileNotFoundException;
/**
 *
 * @author AhmedAli
 */
public class MainframeMidnight extends javax.swing.JFrame{ //replacing varibales with DataStoreMidnight class

    /**
     * Creates new form MainframeMidnight
     */

    private final DataStoreMidnight ds = new DataStoreMidnight(); //replaced every single variable in here with this instantiated object
    
  

            
    
    int timeRun = 0; //This creates a variable with the data type of integer,
                     //The variable 'timeRun' is used within the clock.
    
        public MainframeMidnight()
        {
    
        initComponents();
        new Thread()
        {
            public void run()
            {
               while(timeRun == 0)
                {
                    Calendar cal = new GregorianCalendar(); //Creates a new object from the GregorianCalendar class
                    
                    int hour = cal.get(Calendar.HOUR); //This gets the "HOUR" of time from the computers own internal time.
                    int min = cal.get(Calendar.MINUTE);//This gets the "MINUTE"
                    int sec = cal.get(Calendar.SECOND);//This gets the Second
                    int AM_PM = cal.get(Calendar.AM_PM);
                   
                    
                    String day_night = "";
                    if (AM_PM == 1)     //I used an "if" statement because we have two possible values, 
                                        //AM or PM and we can only have one of them at a time. 
                                        //In this calendar class, AM is represented by a 0 and PM by 1.  
                    {
                        day_night = "PM";
                    }
                    else
                    {   
                        day_night = "AM";
                    } 
                        
                    String time = hour + ":"  + min + ":" + sec + " " + day_night;
                    
                    Clock.setText(time); //Clock is our variable name for the clock in the program. 
                }
            }
        }.start();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGreenseaturtle = new javax.swing.JButton();
        BtnOliveridelyturtle = new javax.swing.JButton();
        BtnMinusoliveridelyturtle = new javax.swing.JButton();
        BtnMinusgreenseaturtle = new javax.swing.JButton();
        BtnMinusbandedseakrait = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBandedseakrait = new javax.swing.JTextField();
        txtGreenseaturtle = new javax.swing.JTextField();
        txtOliveridelyturtle = new javax.swing.JTextField();
        BtnWrasse = new javax.swing.JButton();
        lblRayfinnedfish = new javax.swing.JLabel();
        BtnParrotfish = new javax.swing.JButton();
        BtnMinusparrotfish = new javax.swing.JButton();
        BtnMinuswrasse = new javax.swing.JButton();
        txtWrasse = new javax.swing.JTextField();
        txtParrotfish = new javax.swing.JTextField();
        txtTrout = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        BtnFinish = new javax.swing.JButton();
        Clock = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea1 = new javax.swing.JTextArea();
        BtnDugong = new javax.swing.JButton();
        BtnHumpbackwhale = new javax.swing.JButton();
        lblMammals = new javax.swing.JLabel();
        BtnMinushumpbackwhale = new javax.swing.JButton();
        txtMinusdugong = new javax.swing.JButton();
        txtDugong = new javax.swing.JTextField();
        txtHumpbackwhale = new javax.swing.JTextField();
        lblCephalopods = new javax.swing.JLabel();
        txtOctopus = new javax.swing.JTextField();
        BtnMinusoctopus = new javax.swing.JButton();
        BtnOctopus = new javax.swing.JButton();
        BtnCuttlefish = new javax.swing.JButton();
        BtnMinuscuttlefish = new javax.swing.JButton();
        txtCuttlefish = new javax.swing.JTextField();
        txtSquid = new javax.swing.JTextField();
        BtnMinussquid = new javax.swing.JButton();
        BtnSquid = new javax.swing.JButton();
        lblCartilaginousfish = new javax.swing.JLabel();
        BtnLemonshark = new javax.swing.JButton();
        BtnMinuslemonshark = new javax.swing.JButton();
        txtLemonshark = new javax.swing.JTextField();
        BtnMinushammerheadshark = new javax.swing.JButton();
        BtnHammerheadshark = new javax.swing.JButton();
        BtnWhaleshark = new javax.swing.JButton();
        BtnTigershark = new javax.swing.JButton();
        BtnMinustigershark = new javax.swing.JButton();
        BtnMinuswhaleshark = new javax.swing.JButton();
        txtWhaleshark = new javax.swing.JTextField();
        txtTigershark = new javax.swing.JTextField();
        txtHammerheadshark = new javax.swing.JTextField();
        BtnMinusTrout = new javax.swing.JButton();
        BtnMinusCod = new javax.swing.JButton();
        BtnTrout = new javax.swing.JButton();
        BtnCod = new javax.swing.JButton();
        BtnBandedseakrait = new javax.swing.JButton();
        txtRayfinnedfish = new javax.swing.JTextField();
        txtReptiles = new javax.swing.JTextField();
        txtMammals = new javax.swing.JTextField();
        txtCephalopods = new javax.swing.JTextField();
        txtCartilaginousfish = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGenus = new javax.swing.JTextArea();
        lblRayfinnedfish1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnGreenseaturtle.setText("Green Sea Turtle");
        BtnGreenseaturtle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGreenseaturtleMouseClicked(evt);
            }
        });
        BtnGreenseaturtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGreenseaturtleActionPerformed(evt);
            }
        });

        BtnOliveridelyturtle.setText("Olive Ridely Turtle");
        BtnOliveridelyturtle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnOliveridelyturtleMouseClicked(evt);
            }
        });
        BtnOliveridelyturtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOliveridelyturtleActionPerformed(evt);
            }
        });

        BtnMinusoliveridelyturtle.setText("-");
        BtnMinusoliveridelyturtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusoliveridelyturtleActionPerformed(evt);
            }
        });

        BtnMinusgreenseaturtle.setText("-");
        BtnMinusgreenseaturtle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinusgreenseaturtleMouseClicked(evt);
            }
        });
        BtnMinusgreenseaturtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusgreenseaturtleActionPerformed(evt);
            }
        });

        BtnMinusbandedseakrait.setText("-");
        BtnMinusbandedseakrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinusbandedseakraitMouseClicked(evt);
            }
        });
        BtnMinusbandedseakrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusbandedseakraitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Reptiles");

        txtBandedseakrait.setText("0");
        txtBandedseakrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBandedseakraitActionPerformed(evt);
            }
        });

        txtGreenseaturtle.setText("0");

        txtOliveridelyturtle.setText("0");
        txtOliveridelyturtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOliveridelyturtleActionPerformed(evt);
            }
        });

        BtnWrasse.setText("Wrasse");
        BtnWrasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnWrasseActionPerformed(evt);
            }
        });

        lblRayfinnedfish.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRayfinnedfish.setText("Ray-finned Fish");
        lblRayfinnedfish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRayfinnedfishMouseEntered(evt);
            }
        });

        BtnParrotfish.setText("Parrot Fish");
        BtnParrotfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnParrotfishActionPerformed(evt);
            }
        });

        BtnMinusparrotfish.setText("-");
        BtnMinusparrotfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusparrotfishActionPerformed(evt);
            }
        });

        BtnMinuswrasse.setText("-");
        BtnMinuswrasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinuswrasseActionPerformed(evt);
            }
        });

        txtWrasse.setText("0");
        txtWrasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWrasseActionPerformed(evt);
            }
        });

        txtParrotfish.setText("0");
        txtParrotfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParrotfishActionPerformed(evt);
            }
        });

        txtTrout.setText("0");
        txtTrout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTroutActionPerformed(evt);
            }
        });

        txtCod.setText("0");

        BtnFinish.setText("Finish");
        BtnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFinishActionPerformed(evt);
            }
        });

        Clock.setFont(new java.awt.Font("DS-Digital", 0, 48)); // NOI18N
        Clock.setForeground(new java.awt.Color(255, 0, 0));
        Clock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clock.setText("17:45:06");
        Clock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ClockAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtArea1.setColumns(20);
        txtArea1.setRows(5);
        jScrollPane2.setViewportView(txtArea1);

        BtnDugong.setText("Dugong");
        BtnDugong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDugongActionPerformed(evt);
            }
        });

        BtnHumpbackwhale.setText("HumpBack Whale");
        BtnHumpbackwhale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnHumpbackwhaleMouseClicked(evt);
            }
        });
        BtnHumpbackwhale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHumpbackwhaleActionPerformed(evt);
            }
        });

        lblMammals.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblMammals.setText("Mammals");

        BtnMinushumpbackwhale.setText("-");
        BtnMinushumpbackwhale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinushumpbackwhaleActionPerformed(evt);
            }
        });

        txtMinusdugong.setText("-");
        txtMinusdugong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMinusdugongMouseClicked(evt);
            }
        });
        txtMinusdugong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMinusdugongActionPerformed(evt);
            }
        });

        txtDugong.setText("0");
        txtDugong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDugongActionPerformed(evt);
            }
        });

        txtHumpbackwhale.setText("0");
        txtHumpbackwhale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHumpbackwhaleActionPerformed(evt);
            }
        });

        lblCephalopods.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCephalopods.setText("Cephalopods");
        lblCephalopods.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCephalopodsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        txtOctopus.setText("0");
        txtOctopus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOctopusActionPerformed(evt);
            }
        });

        BtnMinusoctopus.setText("-");
        BtnMinusoctopus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusoctopusActionPerformed(evt);
            }
        });

        BtnOctopus.setText("Octopus");
        BtnOctopus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOctopusActionPerformed(evt);
            }
        });

        BtnCuttlefish.setText("Cuttlefish");
        BtnCuttlefish.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                BtnCuttlefishClockAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        BtnCuttlefish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCuttlefishActionPerformed(evt);
            }
        });

        BtnMinuscuttlefish.setText("-");
        BtnMinuscuttlefish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinuscuttlefishActionPerformed(evt);
            }
        });

        txtCuttlefish.setText("0");
        txtCuttlefish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuttlefishActionPerformed(evt);
            }
        });

        txtSquid.setText("0");

        BtnMinussquid.setText("-");
        BtnMinussquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinussquidActionPerformed(evt);
            }
        });

        BtnSquid.setText("Squid");
        BtnSquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSquidActionPerformed(evt);
            }
        });

        lblCartilaginousfish.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCartilaginousfish.setText("Cartilaginous Fish");
        lblCartilaginousfish.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCartilaginousfishAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        BtnLemonshark.setText("Lemon Shark");
        BtnLemonshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLemonsharkActionPerformed(evt);
            }
        });

        BtnMinuslemonshark.setText("-");
        BtnMinuslemonshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinuslemonsharkActionPerformed(evt);
            }
        });

        txtLemonshark.setText("0");

        BtnMinushammerheadshark.setText("-");
        BtnMinushammerheadshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinushammerheadsharkActionPerformed(evt);
            }
        });

        BtnHammerheadshark.setText("Hammerhead Shark");
        BtnHammerheadshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHammerheadsharkActionPerformed(evt);
            }
        });

        BtnWhaleshark.setText("Whale Shark");
        BtnWhaleshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnWhalesharkActionPerformed(evt);
            }
        });

        BtnTigershark.setText("Tiger Shark");
        BtnTigershark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTigersharkActionPerformed(evt);
            }
        });

        BtnMinustigershark.setText("-");
        BtnMinustigershark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinustigersharkActionPerformed(evt);
            }
        });

        BtnMinuswhaleshark.setText("-");
        BtnMinuswhaleshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinuswhalesharkActionPerformed(evt);
            }
        });

        txtWhaleshark.setText("0");

        txtTigershark.setText("0");

        txtHammerheadshark.setText("0");
        txtHammerheadshark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHammerheadsharkActionPerformed(evt);
            }
        });

        BtnMinusTrout.setText("-");
        BtnMinusTrout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinusTroutMouseClicked(evt);
            }
        });
        BtnMinusTrout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusTroutActionPerformed(evt);
            }
        });

        BtnMinusCod.setText("-");
        BtnMinusCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMinusCodMouseClicked(evt);
            }
        });
        BtnMinusCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMinusCodActionPerformed(evt);
            }
        });

        BtnTrout.setText("Trout");
        BtnTrout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnTroutMouseClicked(evt);
            }
        });
        BtnTrout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTroutActionPerformed(evt);
            }
        });

        BtnCod.setText("Cod");
        BtnCod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnCodMouseClicked(evt);
            }
        });
        BtnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCodActionPerformed(evt);
            }
        });

        BtnBandedseakrait.setText("Banded Sea Krait");
        BtnBandedseakrait.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnBandedseakraitMouseClicked(evt);
            }
        });
        BtnBandedseakrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBandedseakraitActionPerformed(evt);
            }
        });

        txtRayfinnedfish.setText("0");

        txtReptiles.setText("0");
        txtReptiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReptilesActionPerformed(evt);
            }
        });

        txtMammals.setText("0");

        txtCephalopods.setText("0");

        txtCartilaginousfish.setText("0");

        txtGenus.setColumns(20);
        txtGenus.setRows(5);
        jScrollPane1.setViewportView(txtGenus);

        lblRayfinnedfish1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRayfinnedfish1.setText("Genus Information");
        lblRayfinnedfish1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRayfinnedfish1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnWrasse, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnParrotfish, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnTrout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BtnMinuswrasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnMinusparrotfish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(BtnMinusCod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(BtnMinusTrout, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(lblRayfinnedfish)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRayfinnedfish, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addComponent(txtReptiles, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnGreenseaturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(BtnOliveridelyturtle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnBandedseakrait, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BtnMinusoliveridelyturtle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnMinusgreenseaturtle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnMinusbandedseakrait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(lblRayfinnedfish1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtGreenseaturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtBandedseakrait, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtOliveridelyturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(87, 87, 87)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblMammals)
                                                    .addComponent(BtnHumpbackwhale, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(BtnMinushumpbackwhale)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtHumpbackwhale, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(txtMammals, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(BtnDugong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMinusdugong)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDugong, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtParrotfish, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtWrasse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrout, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Clock, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(BtnFinish)
                                        .addGap(89, 89, 89)))
                                .addGap(74, 74, 74))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(BtnCuttlefish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnOctopus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(BtnSquid, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BtnMinuscuttlefish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtnMinusoctopus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(BtnMinussquid))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCartilaginousfish)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCartilaginousfish, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblCephalopods)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtCuttlefish, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                                .addComponent(txtSquid))
                                            .addComponent(txtOctopus, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCephalopods, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnLemonshark, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnHammerheadshark, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnMinushammerheadshark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnMinuslemonshark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLemonshark)
                                    .addComponent(txtHammerheadshark))))
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnTigershark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnWhaleshark, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnMinustigershark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnMinuswhaleshark))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTigershark, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWhaleshark))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCephalopods)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblMammals)
                                .addComponent(txtMammals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCephalopods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnHumpbackwhale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinushumpbackwhale, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHumpbackwhale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnOctopus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinusoctopus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOctopus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnDugong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMinusdugong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDugong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCuttlefish, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinuscuttlefish, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCuttlefish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSquid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinussquid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSquid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtReptiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnMinusbandedseakrait, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnBandedseakrait, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBandedseakrait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnMinusgreenseaturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BtnGreenseaturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGreenseaturtle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOliveridelyturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinusoliveridelyturtle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtOliveridelyturtle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblRayfinnedfish)
                                    .addComponent(txtRayfinnedfish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtWrasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnWrasse, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                    .addComponent(BtnMinuswrasse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnParrotfish, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMinusparrotfish, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtParrotfish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnTrout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMinusTrout, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTrout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnMinusCod, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Clock, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnFinish)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblRayfinnedfish1)
                                        .addGap(12, 12, 12)
                                        .addGap(78, 78, 78))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCartilaginousfish)
                            .addComponent(txtCartilaginousfish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnLemonshark, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(txtLemonshark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinuslemonshark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnHammerheadshark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinushammerheadshark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHammerheadshark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnTigershark, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnMinustigershark, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTigershark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(txtWhaleshark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnMinuswhaleshark, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnWhaleshark, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 57, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGreenseaturtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGreenseaturtleActionPerformed
        txtArea1.setText(ds.increment("greenseaturtle"));
        txtGreenseaturtle.setText(ds.increment("greenseaturtlecount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnGreenseaturtleActionPerformed

    private void BtnMinusgreenseaturtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusgreenseaturtleActionPerformed
        txtArea1.setText(ds.increment("greenseaturtleminus"));
        txtGreenseaturtle.setText(ds.increment("greenseaturtlecount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnMinusgreenseaturtleActionPerformed

    private void BtnMinusbandedseakraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusbandedseakraitActionPerformed
    
    }//GEN-LAST:event_BtnMinusbandedseakraitActionPerformed

    private void txtBandedseakraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBandedseakraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBandedseakraitActionPerformed

    private void BtnWrasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWrasseActionPerformed
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        txtArea1.setText(ds.increment("wrasse"));
        txtWrasse.setText(ds.increment("wrassecount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
    }//GEN-LAST:event_BtnWrasseActionPerformed

    private void lblRayfinnedfishMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRayfinnedfishMouseEntered

    }//GEN-LAST:event_lblRayfinnedfishMouseEntered

    private void BtnParrotfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnParrotfishActionPerformed
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        txtArea1.setText(ds.increment("parrotfish"));
        txtParrotfish.setText(ds.increment("parrotfishcount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
    }//GEN-LAST:event_BtnParrotfishActionPerformed

    private void BtnMinusparrotfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusparrotfishActionPerformed
        
        txtArea1.setText(ds.increment("parrotfishminus"));
        txtParrotfish.setText(ds.increment("parrotfishcount")); //The reason why we put a count version in there is to make the "parrotfish count" method happen which simply prints the count of parrot fish that exist so far 
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
    }//GEN-LAST:event_BtnMinusparrotfishActionPerformed

    private void BtnMinuswrasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinuswrasseActionPerformed
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        txtArea1.setText(ds.increment("wrasseminus"));
        txtWrasse.setText(ds.increment("wrassecount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
    }//GEN-LAST:event_BtnMinuswrasseActionPerformed

    private void txtWrasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWrasseActionPerformed
        
    }//GEN-LAST:event_txtWrasseActionPerformed

    private void BtnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFinishActionPerformed
        String fileName = "FishMidnightResultsout.txt";
        try
        {
            PrintWriter outputStream = new PrintWriter(fileName);
            outputStream.println("Findings of Oxford University Department of Marine Biology research survey:"); //stores information in RAM first
            outputStream.println(ds.increment("rayfinnedfishprint"));
            outputStream.println(ds.increment("wrasseprint"));
            outputStream.println(ds.increment("parrotfishprint"));
            outputStream.println(ds.increment("troutprint"));
            outputStream.println(ds.increment("codprint"));
            outputStream.println(ds.increment("reptileprint"));
            outputStream.println(ds.increment("bandedseakraitprint"));
            outputStream.println(ds.increment("greenseaturtleprint"));
            outputStream.println(ds.increment("oliveridelyturtleprint"));
            outputStream.println(ds.increment("mammalsprint"));
            outputStream.println(ds.increment("humpbackwhaleprint"));
            outputStream.println(ds.increment("dugongprint"));
            outputStream.println(ds.increment("cephalopodsprint"));
            outputStream.println(ds.increment("octopusprint"));
            outputStream.println(ds.increment("cuttlefishprint"));
            outputStream.println(ds.increment("squidprint"));
            outputStream.println(ds.increment("cartilaginousfishprint"));
            outputStream.println(ds.increment("lemonsharkprint"));
            outputStream.println(ds.increment("hammerheadsharkprint"));
            outputStream.println(ds.increment("tigersharkprint"));
            outputStream.println(ds.increment("whalesharkprint"));

            Calendar cal2 = new GregorianCalendar();
            int date = cal2.get(Calendar.DATE);
            int month = cal2.get(Calendar.MONTH) + 1;
            int year = cal2.get(Calendar.YEAR);
            outputStream.println("Date of experiment: " + date + "/" + month + "/" + year);
            outputStream.close(); //flushes the data to the file
            System.out.println("Done!");

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_BtnFinishActionPerformed

    private void ClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ClockAncestorAdded

    private void BtnDugongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDugongActionPerformed
       
        txtArea1.setText(ds.increment("dugong"));
        txtDugong.setText(ds.increment("dugongcount"));
        txtMammals.setText(ds.increment("mammals"));
        txtGenus.setText(ds.increment("mammalgenus"));
    }//GEN-LAST:event_BtnDugongActionPerformed

    private void BtnHumpbackwhaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHumpbackwhaleActionPerformed
        txtArea1.setText(ds.increment("humpbackwhale"));
        txtHumpbackwhale.setText(ds.increment("humpbackwhalecount"));
        txtMammals.setText(ds.increment("mammals"));
        txtGenus.setText(ds.increment("mammalgenus"));
        
    }//GEN-LAST:event_BtnHumpbackwhaleActionPerformed

    private void BtnMinushumpbackwhaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinushumpbackwhaleActionPerformed
   
        txtArea1.setText(ds.increment("humpbackwhaleminus"));
        txtHumpbackwhale.setText(ds.increment("humpbackwhalecount"));
        txtMammals.setText(ds.increment("mammals"));
        txtGenus.setText(ds.increment("mammalgenus"));
       
    }//GEN-LAST:event_BtnMinushumpbackwhaleActionPerformed

    private void txtMinusdugongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMinusdugongActionPerformed

       txtArea1.setText(ds.increment("dugongminus"));
       txtDugong.setText(ds.increment("dugongcount"));
       txtMammals.setText(ds.increment("mammals"));
       txtGenus.setText(ds.increment("mammalgenus"));

    }//GEN-LAST:event_txtMinusdugongActionPerformed

    private void txtDugongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDugongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDugongActionPerformed

    private void txtHumpbackwhaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHumpbackwhaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHumpbackwhaleActionPerformed

    private void lblCephalopodsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCephalopodsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCephalopodsAncestorAdded

    private void txtOctopusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOctopusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOctopusActionPerformed

    private void BtnMinusoctopusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusoctopusActionPerformed

       txtArea1.setText(ds.increment("octopusminus"));
       txtOctopus.setText(ds.increment("octopuscount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnMinusoctopusActionPerformed

    private void BtnOctopusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOctopusActionPerformed

       txtArea1.setText(ds.increment("octopus"));
       txtOctopus.setText(ds.increment("octopuscount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnOctopusActionPerformed

    private void BtnCuttlefishClockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_BtnCuttlefishClockAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCuttlefishClockAncestorAdded

    private void BtnCuttlefishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCuttlefishActionPerformed
 
       txtArea1.setText(ds.increment("cuttlefish"));
       txtCuttlefish.setText(ds.increment("cuttlefishcount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnCuttlefishActionPerformed

    private void BtnMinuscuttlefishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinuscuttlefishActionPerformed
        
       txtArea1.setText(ds.increment("cuttlefishminus"));
       txtCuttlefish.setText(ds.increment("cuttlefishcount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnMinuscuttlefishActionPerformed

    private void txtCuttlefishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuttlefishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuttlefishActionPerformed

    private void BtnMinussquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinussquidActionPerformed
       txtArea1.setText(ds.increment("squidminus"));
       txtSquid.setText(ds.increment("squidcount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnMinussquidActionPerformed

    private void BtnSquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSquidActionPerformed
       txtArea1.setText(ds.increment("squid"));
       txtSquid.setText(ds.increment("squidcount"));
       txtCephalopods.setText(ds.increment("cephalopods"));
       txtGenus.setText(ds.increment("cephalopodsgenus"));
    }//GEN-LAST:event_BtnSquidActionPerformed

    private void lblCartilaginousfishAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCartilaginousfishAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCartilaginousfishAncestorAdded

    private void BtnLemonsharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLemonsharkActionPerformed
       txtArea1.setText(ds.increment("lemonshark"));
       txtLemonshark.setText(ds.increment("lemonsharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish"));
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnLemonsharkActionPerformed

    private void BtnMinuslemonsharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinuslemonsharkActionPerformed
       txtArea1.setText(ds.increment("lemonsharkminus"));
       txtLemonshark.setText(ds.increment("lemonsharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish"));
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnMinuslemonsharkActionPerformed

    private void BtnMinushammerheadsharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinushammerheadsharkActionPerformed
       txtArea1.setText(ds.increment("hammerheadsharkminus"));
       txtHammerheadshark.setText(ds.increment("hammerheadsharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish"));
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnMinushammerheadsharkActionPerformed

    private void BtnHammerheadsharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHammerheadsharkActionPerformed
       txtArea1.setText(ds.increment("hammerheadshark"));
       txtHammerheadshark.setText(ds.increment("hammerheadsharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish")); 
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnHammerheadsharkActionPerformed

    private void BtnWhalesharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnWhalesharkActionPerformed
       txtArea1.setText(ds.increment("whaleshark"));
       txtWhaleshark.setText(ds.increment("whalesharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish")); 
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnWhalesharkActionPerformed

    private void BtnTigersharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTigersharkActionPerformed
       txtArea1.setText(ds.increment("tigershark"));
       txtTigershark.setText(ds.increment("tigersharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish"));
       txtGenus.setText(ds.increment("cartilaginousfishgenus")); 
    }//GEN-LAST:event_BtnTigersharkActionPerformed

    private void BtnMinustigersharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinustigersharkActionPerformed
       txtArea1.setText(ds.increment("tigersharkminus"));
       txtTigershark.setText(ds.increment("tigersharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish"));
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnMinustigersharkActionPerformed

    private void BtnMinuswhalesharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinuswhalesharkActionPerformed
       txtArea1.setText(ds.increment("whalesharkminus"));
       txtWhaleshark.setText(ds.increment("whalesharkcount"));
       txtCartilaginousfish.setText(ds.increment("cartilaginousfish")); 
       txtGenus.setText(ds.increment("cartilaginousfishgenus"));
    }//GEN-LAST:event_BtnMinuswhalesharkActionPerformed

    private void txtHammerheadsharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHammerheadsharkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHammerheadsharkActionPerformed

    private void BtnMinusTroutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusTroutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMinusTroutActionPerformed

    private void BtnMinusTroutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinusTroutMouseClicked
       
        txtArea1.setText(ds.increment("troutminus")); //the troutminus calls the troutminus method 
        txtTrout.setText(ds.increment("troutcount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        
    }//GEN-LAST:event_BtnMinusTroutMouseClicked

    private void txtParrotfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParrotfishActionPerformed
       
    }//GEN-LAST:event_txtParrotfishActionPerformed

    private void BtnMinusCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinusCodMouseClicked
        
        txtArea1.setText(ds.increment("codminus"));
        txtCod.setText(ds.increment("codcount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
    }//GEN-LAST:event_BtnMinusCodMouseClicked

    private void BtnMinusCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMinusCodActionPerformed

    private void txtTroutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTroutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTroutActionPerformed

    private void BtnTroutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTroutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTroutActionPerformed

    private void BtnTroutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnTroutMouseClicked
        txtArea1.setText(ds.increment("trout"));
        txtTrout.setText(ds.increment("troutcount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
    }//GEN-LAST:event_BtnTroutMouseClicked

    private void BtnCodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnCodMouseClicked
        txtArea1.setText(ds.increment("cod"));
        txtCod.setText(ds.increment("codcount"));
        txtRayfinnedfish.setText(ds.increment("rayfinnedfish"));
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
    }//GEN-LAST:event_BtnCodMouseClicked

    private void BtnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCodActionPerformed

    private void BtnBandedseakraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBandedseakraitActionPerformed
        txtArea1.setText(ds.increment("bandedseakrait"));
        txtBandedseakrait.setText(ds.increment("bandedseakraitcount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnBandedseakraitActionPerformed

    private void BtnBandedseakraitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnBandedseakraitMouseClicked
        
    }//GEN-LAST:event_BtnBandedseakraitMouseClicked

    private void BtnMinusbandedseakraitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinusbandedseakraitMouseClicked
        txtArea1.setText(ds.increment("bandedseakraitminus"));
        txtBandedseakrait.setText(ds.increment("bandedseakraitcount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("rayfinnedfishgenus"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnMinusbandedseakraitMouseClicked

    private void txtOliveridelyturtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOliveridelyturtleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOliveridelyturtleActionPerformed

    private void BtnMinusoliveridelyturtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMinusoliveridelyturtleActionPerformed
        txtArea1.setText(ds.increment("oliveridelyturtleminus"));
        txtOliveridelyturtle.setText(ds.increment("oliveridelyturtlecount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnMinusoliveridelyturtleActionPerformed

    private void BtnOliveridelyturtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOliveridelyturtleActionPerformed
        txtArea1.setText(ds.increment("oliveridelyturtle"));
        txtOliveridelyturtle.setText(ds.increment("oliveridelyturtlecount"));
        txtReptiles.setText(ds.increment("reptiles"));
        txtGenus.setText(ds.increment("reptilegenus"));
    }//GEN-LAST:event_BtnOliveridelyturtleActionPerformed

    private void BtnOliveridelyturtleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnOliveridelyturtleMouseClicked

    }//GEN-LAST:event_BtnOliveridelyturtleMouseClicked

    private void BtnGreenseaturtleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGreenseaturtleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGreenseaturtleMouseClicked

    private void BtnMinusgreenseaturtleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMinusgreenseaturtleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMinusgreenseaturtleMouseClicked

    private void txtReptilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReptilesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReptilesActionPerformed

    private void BtnHumpbackwhaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnHumpbackwhaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnHumpbackwhaleMouseClicked

    private void txtMinusdugongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMinusdugongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMinusdugongMouseClicked

    private void lblRayfinnedfish1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRayfinnedfish1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRayfinnedfish1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainframeMidnight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainframeMidnight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainframeMidnight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainframeMidnight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainframeMidnight().setVisible(true);
            }
        }); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBandedseakrait;
    private javax.swing.JButton BtnCod;
    private javax.swing.JButton BtnCuttlefish;
    private javax.swing.JButton BtnDugong;
    private javax.swing.JButton BtnFinish;
    private javax.swing.JButton BtnGreenseaturtle;
    private javax.swing.JButton BtnHammerheadshark;
    private javax.swing.JButton BtnHumpbackwhale;
    private javax.swing.JButton BtnLemonshark;
    private javax.swing.JButton BtnMinusCod;
    private javax.swing.JButton BtnMinusTrout;
    private javax.swing.JButton BtnMinusbandedseakrait;
    private javax.swing.JButton BtnMinuscuttlefish;
    private javax.swing.JButton BtnMinusgreenseaturtle;
    private javax.swing.JButton BtnMinushammerheadshark;
    private javax.swing.JButton BtnMinushumpbackwhale;
    private javax.swing.JButton BtnMinuslemonshark;
    private javax.swing.JButton BtnMinusoctopus;
    private javax.swing.JButton BtnMinusoliveridelyturtle;
    private javax.swing.JButton BtnMinusparrotfish;
    private javax.swing.JButton BtnMinussquid;
    private javax.swing.JButton BtnMinustigershark;
    private javax.swing.JButton BtnMinuswhaleshark;
    private javax.swing.JButton BtnMinuswrasse;
    private javax.swing.JButton BtnOctopus;
    private javax.swing.JButton BtnOliveridelyturtle;
    private javax.swing.JButton BtnParrotfish;
    private javax.swing.JButton BtnSquid;
    private javax.swing.JButton BtnTigershark;
    private javax.swing.JButton BtnTrout;
    private javax.swing.JButton BtnWhaleshark;
    private javax.swing.JButton BtnWrasse;
    private javax.swing.JLabel Clock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCartilaginousfish;
    private javax.swing.JLabel lblCephalopods;
    private javax.swing.JLabel lblMammals;
    private javax.swing.JLabel lblRayfinnedfish;
    private javax.swing.JLabel lblRayfinnedfish1;
    private javax.swing.JTextArea txtArea1;
    private javax.swing.JTextField txtBandedseakrait;
    private javax.swing.JTextField txtCartilaginousfish;
    private javax.swing.JTextField txtCephalopods;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCuttlefish;
    private javax.swing.JTextField txtDugong;
    private javax.swing.JTextArea txtGenus;
    private javax.swing.JTextField txtGreenseaturtle;
    private javax.swing.JTextField txtHammerheadshark;
    private javax.swing.JTextField txtHumpbackwhale;
    private javax.swing.JTextField txtLemonshark;
    private javax.swing.JTextField txtMammals;
    private javax.swing.JButton txtMinusdugong;
    private javax.swing.JTextField txtOctopus;
    private javax.swing.JTextField txtOliveridelyturtle;
    private javax.swing.JTextField txtParrotfish;
    private javax.swing.JTextField txtRayfinnedfish;
    private javax.swing.JTextField txtReptiles;
    private javax.swing.JTextField txtSquid;
    private javax.swing.JTextField txtTigershark;
    private javax.swing.JTextField txtTrout;
    private javax.swing.JTextField txtWhaleshark;
    private javax.swing.JTextField txtWrasse;
    // End of variables declaration//GEN-END:variables
}
